# Generated by Django 2.1.7 on 2019-11-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191108_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
