# Generated by Django 2.1.7 on 2019-11-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
