# Generated by Django 2.1.7 on 2020-05-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('file_url', models.URLField(help_text='文件url', verbose_name='文件url')),
                ('title', models.CharField(help_text='文档标题', max_length=150, verbose_name='文档标题')),
                ('desc', models.TextField(help_text='文档描述', verbose_name='文档描述')),
                ('image_url', models.URLField(default='', help_text='图片url', verbose_name='图片url')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_docs',
            },
        ),
    ]
