# Generated by Django 2.1.7 on 2020-04-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200421_0251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='tb_comment',
        ),
    ]
