# Generated by Django 2.1.7 on 2020-05-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('title', models.CharField(max_length=80, verbose_name='课程名字')),
                ('cover_url', models.URLField(verbose_name='课程封面url')),
                ('video_url', models.URLField(verbose_name='视频url')),
                ('duration', models.FloatField(default=0.0, verbose_name='视频时长')),
                ('profile', models.TextField(blank=True, null=True, verbose_name='课程简介')),
                ('outline', models.TextField(blank=True, null=True, verbose_name='课程大纲')),
            ],
            options={
                'verbose_name': '课程详情',
                'db_table': 'tb_course',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=80, verbose_name='课程分类')),
            ],
            options={
                'verbose_name': '课程分类',
                'db_table': 'tb_course_category',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=50, verbose_name='讲师姓名')),
                ('positional_title', models.CharField(max_length=150, verbose_name='职称')),
                ('profile', models.TextField(verbose_name='讲师简介')),
                ('avatar_url', models.URLField(default='', verbose_name='头像url')),
            ],
            options={
                'verbose_name': '讲师',
                'db_table': 'tb_teachers',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.CourseCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Teacher'),
        ),
    ]
